# Generated by Django 5.1.3 on 2024-11-27 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('sender', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company_of_sender', models.CharField(max_length=100)),
                ('unique_email_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
