# Generated by Django 5.1.3 on 2024-11-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
