# Generated by Django 5.1.3 on 2024-11-29 15:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_email_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='unique_email_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
